import * as esbuild from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';

const DIST = 'dist';

// Ensure clean dist/
fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(DIST, { recursive: true });
fs.mkdirSync(path.join(DIST, 'icons'), { recursive: true });

const commonOptions = {
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'chrome120',
  treeShaking: true,
  minify: false,        // keep readable for Chrome Web Store review
  sourcemap: false,
};

// ── Content-script bundles (injected via chrome.scripting) ──
const contentEntries = [
  'src/content/core-lib.js',
  'src/content/dxf-writer.js',
  'src/content/acad-writers.js',
  'src/content/run-export.js',
];

for (const entry of contentEntries) {
  const outName = path.basename(entry);
  await esbuild.build({
    ...commonOptions,
    entryPoints: [entry],
    outfile: path.join(DIST, outName),
  });
  console.log(`  ✔ ${outName}`);
}

// ── Popup ──
await esbuild.build({
  ...commonOptions,
  entryPoints: ['src/popup/popup.js'],
  outfile: path.join(DIST, 'popup.js'),
});
console.log('  ✔ popup.js');

// ── Service worker ──
await esbuild.build({
  ...commonOptions,
  entryPoints: ['src/background/service-worker.js'],
  outfile: path.join(DIST, 'service-worker.js'),
});
console.log('  ✔ service-worker.js');

// ── Copy static assets ──
const statics = [
  ['manifest.json', 'manifest.json'],
  ['src/popup/popup.html', 'popup.html'],
  ['src/popup/popup.css', 'popup.css'],
];

for (const [src, dest] of statics) {
  fs.copyFileSync(src, path.join(DIST, dest));
  console.log(`  ✔ ${dest} (copy)`);
}

// Copy icons if they exist (generated by build:icons)
const iconsDir = path.join(DIST, 'icons');
for (const size of [16, 32, 48, 128]) {
  const name = `icon${size}.png`;
  const src = path.join('src', 'icons', name);
  if (fs.existsSync(src)) {
    fs.copyFileSync(src, path.join(iconsDir, name));
    console.log(`  ✔ icons/${name} (copy)`);
  }
}

console.log('\nBuild complete → dist/');
